# image will be published to ghcr.io/<user>/<name>
name: vlm-ublue-os-laptop
# description will be included in the image's metadata
description: uBlue-based image for user valmar (vlm) - laptop version

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - tailscale
      # - micro
      # - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      # - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section


  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                  #  will be installed and set up
    # custom-flatpaks: # this section is optional
        # - Celluloid: io.github.celluloid_player.Celluloid
        # - Krita: org.kde.krita

  - type: default-flatpaks
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.bitwarden.desktop
        - com.calibre_ebook.calibre
        - com.github.jeromerobert.pdfarranger
        - com.github.johnfactotum.Foliate
        - com.github.tchx84.Flatseal
        - com.github.zocker_160.SyncThingy
        - com.google.Chrome
        - com.logseq.Logseq
        - com.makemkv.MakeMKV
        - com.mastermindzh.tidal-hifi
        - com.mattjakeman.ExtensionManager
        - com.microsoft.Edge
        - com.raggesilver.BlackBox
        - com.skype.Client
        - com.slack.Slack
        - com.tutanota.Tutanota
        - com.visualstudio.code
        - com.vivaldi.Vivaldi
        - de.haeckerfelix.Shortwave
        - io.bassi.Amberol
        - io.github.celluloid_player.Celluloid
        - io.github.dweymouth.supersonic
        - io.github.flattool.Warehouse
        - io.github.realmazharhussain.GdmSettings
        - io.gitlab.news_flash.NewsFlash
        - io.podman_desktop.PodmanDesktop
        - net.cozic.joplin_desktop
        - net.mullvad.MullvadBrowser
        - org.bunkus.mkvtoolnix-gui
        - org.fedoraproject.MediaWriter
        - org.gnome.baobab
        - org.gnome.Boxes
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Cheese
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Epiphany
        - org.gnome.Evince
        - org.gnome.Evolution
        - org.gnome.Extensions
        - org.gnome.font-viewer
        - org.gnome.Geary
        - org.gnome.gitlab.somas.Apostrophe
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - org.nickvision.tagger
        - org.signal.Signal
        - org.telegram.desktop
        - us.zoom.Zoom

  - type: systemd
    system:
      enabled:
        - tailscaled.service

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
